name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Upload SDS Build Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: Smart Direct Service
          path: /home/runner/work/Smart-Direct-Service/Smart-Direct-Service/bin/Release/net4.7.2/Smart Direct Service.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: GitHub Upload Release Artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
          args: /home/runner/work/Smart-Direct-Service/Smart-Direct-Service/bin/Release/net4.7.2/Smart Direct Service.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
