name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Source"
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: cd ${{ github.workspace }}

      - run: pwd

      - name: Create Build Directory
        run: mkdir _build

      - run: nuget restore "Smart Direct Service.sln"

      - name: Build Solution
        run: |
          msbuild.exe "Smart Direct Service.sln" /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"

      - uses: papeloto/action-zip@v1
        with:
          files: ${{ github.workspace }}/bin/Release/net4.7.2
          recursive: false
          dest: ${{ github.workspace }}/build.zip

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/build.zip
