name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Source"
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _build

      - run: nuget restore "Smart Direct Service.sln"

      - name: Build Solution
        run: |
          msbuild.exe "Smart Direct Service.sln" /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

      - uses: papeloto/action-zip@v1
        with:
          files: _build
          recursive: true
          dest: build.zip

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ./_build
