---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Download artifact
        uses: aochmann/actions-download-artifact@1.0.0
        with:
          # Optional, GitHub token
          github_token: ${{secrets.GITHUB_TOKEN}}

          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: my_artifact

          # Optional, download latest artifact
          latest: true

          # Optional, directory where to extract artifact
          path: ${{ github.workspace }}

          # Optional, defaults to current repo
          repo: ${{github.repository}}
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            my_artifact.zip
