---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      # ...
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: .NET
          workflow_conclusion: completed,success
          commit: d66ea2a59a236aa06fc8ff98f2aaae3da05fdf21
          branch: master
          event: push
          name: my_artifact

      - name: Display structure of downloaded files
        run: ls -R

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            my_artifact.zip
